version: "3.7"

services:
  postgres-db:
    image: diamol/postgres:11.5
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5435:5432"
    volumes:
      - type: bind
        source: ../data/postgres
        target: /var/lib/postgresql/data 
    networks:
      - app-net

  todo-web:
    image: diamol/ch06-todo-list
    restart: unless-stopped
    ports: 
      - "8035:80"
    networks:
      - app-net
    environment:
      - Database:Provider=Postgres
    depends_on:
      - postgres-db
    secrets:
      - source: postgres-connection
        target: /app/config/secrets.json

secrets:
  postgres-connection:
    file: ./postgres-connection.json

networks:
  app-net:
    external:
      name: nat


